# Generated by Django 5.0.1 on 2024-01-31 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_course_owner_lesson_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lesson',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
